### ISSUE TITLE
tests are only running in iphone sim

### ISSUE THREAD

**Issue by brianleroux** [brianleroux/xui#12]
- need to run on BB sim
- need to run on Android sim
- need to run on Palm sim
- need to run on Nokia sim

**Comment by filmaj** [comment]
for some reason only the first two 'modules' of tests are being executed on the blackberry (running core.html specs...)... wtf...

**Comment by filmaj** [comment]
for fucks sake... not all the tests are compatible' on blackberry - going to have to re-write some tests. You know your JS engine fails when you can't run simple fucking qunit tests on it
