### ISSUE TITLE
eventing: no unbind in core

### ISSUE THREAD

**Issue by brianleroux** [brianleroux/xui#14]
- this is fail

**Comment by remy** [comment]
Should the event model from "more" come in to base to enable the unbinding and give us a complete event model at the same time?

Or do we add a simple method as so:

<pre><code>xui.fn.un = function (type, fn) {
  return this.each(function () {
    this.removeEventListener(type, fn, false);
  });
};</code></pre>

**Comment by brianleroux** [comment]
I'm thinking un belongs in core... its an important feature. moving in closing. more should probably have more helpers for things like: swipe, pinch, etc
