### ISSUE TITLE
submodule in sizzle

### ISSUE THREAD

**Issue by brianleroux** [brianleroux/xui#21]
...

**Comment by remy** [comment]
This should be in more rather than base, otherwise, obviously, it'll blow the foot print.

I'm also going to tweak the core/base to support simple selectors to avoid using querySelectorAll - i.e. so that $('#foo').find('div') works with qsa.

**Comment by filmaj** [comment]
I don't think it will be in all 'more' builds either - it will just be included for platform targets that don't support querySelectorAll very well (BlackBerry, some Symbian phones, IE mobile et al). I think it's just a submodule for now until James Burke helps us with the dependency resolution

**Comment by brianleroux** [comment]
exactly

**Comment by remy** [comment]
Just to clarify, you're not expecting to build a collection of playpen specific libraries are you? I understand dynamic library adaption (ie lazy loading sizzle if its required and there's no qsa). For the mobile game I've written already, I want it running, without any browser sniffing, from the same single core xui.

Or have I missed a beat here?

**Comment by brianleroux** [comment]
Plan is to build out playpen specific ones ---- one for each platform... tho I'm open to debate obviously --- jump into irc
