### ISSUE TITLE
Rake build fail

### ISSUE THREAD

**Issue by bryanrieger** [brianleroux/xui#25]
Grabbed a fresh version of XUI today and attempted to build, receive the following error:

> No such file or directory - /Users/bryanrieger/Tools/xui/packages/emile/emile.js
> /Users/bryanrieger/Tools/xui/Rakefile:143:in `initialize'

Apparently 'emile.js' is missing from 'packages' (as I suspect are files related to qunit, shoulda-js and sizzle - those directories are also currently empty).

**Comment by brianleroux** [comment]
hey dude, you need to:

git submodule init; git submodule update

which will pull in the dependant repos

**Comment by bryanrieger** [comment]
Thanks! As you might suspect I'm new here.

**Comment by sepidol** [comment]
i'm freshly clone the repo (20100525), and has execute the git submodule init 
when updating the submodule, it show some error:
fatal: reference is not a tree: 97cec22794f8148da7273d950e8d1cdd192b55fe
Unable to checkout '97cec22794f8148da7273d950e8d1cdd192b55fe' in submodule path 'packages/emile'

any suggestion?
