### ISSUE TITLE
ReferenceError: Can't find variable: $. Line 1065

### ISSUE THREAD

**Issue by gcoop** [brianleroux/xui#26]
On orientation change for older browsers xUI throws this reference error.

ReferenceError: Can't find variable: $. Line 1065

Line 1065:
$('body').fire('orientationchange'); // will this bubble up?

Needs to be:
x$('body').fire('orientationchange'); // will this bubble up?

Thanks.

**Comment by remy** [comment]
Should be xui('body').fire... - it'll compress that way.

**Comment by gcoop** [comment]
my bad :)
