### ISSUE TITLE
element-type selectors are fucked on BlackBerry

### ISSUE THREAD

**Issue by filmaj** [brianleroux/xui#32]
Selectors like this:
    #blah a
don't work. BUT! give the anchor tags a class and then select with this:
    #blah a.somerandomclass
works!

wtf eh? I'll try to tackle this at some point in the distant future.

**Comment by marcreynolds** [comment]
+1 on this issue... is there some initialization that needs to be done before this works?  I noticed that inside the find(c,d) method, there is a conditional checking whether Sizzle is undefined.  Does something need to happen with Sizzle before it can be used?  Would the Sizzle method work with the above selector?

**Comment by filmaj** [comment]
There's a build profile in the rakefile that will submodule-in Sizzle for the blackberry build. This may very well be problem with Sizzle on BlackBerries and not with xui, actually...

**Comment by brianleroux** [comment]
hey guys, if you still see this issue w/ the bb builds (on xuijs.com) let us know at the new repo (http://github.com/xui/xui) and we'll fix asap
