### ISSUE TITLE
Rake or build?

### ISSUE THREAD

**Issue by remy** [brianleroux/xui#33]
All - this is fairly important, I'm trying to fix bugs in the event system but I'm not sure which build I'm supposed to be testing against.

Building with (requirejs) build.sh build profile=enchilada gives me errors throughout the the DOM tests, but building with rake min gives me a 1k additional overhead in the build.

So which are we going with?  If requirejs, I'll see if I can fix the DOM errors.

**Comment by remy** [comment]
Actually, I've just been looking in more detail - the requirejs build is screwed - it doesn't top and tail the code in an anonymous function, which causes all the helper functions to go global. On top of that, all the variables set up in base.js aren't being exposed properly.

I _think_ that this can be just fixed by tailing the rest of the includes with })(); but I don't really know how the requirejs system works. 

Any thoughts on how to fix this?

**Comment by remy** [comment]
Okay, so apparently I just needed to sound out my problem to fix it!

I've added an explicit header & footer script which tops and tails, and creates the private scope we need to get the requirejs build working.

None the less - should we remove all references to the rake scripts now?

**Comment by brianleroux** [comment]
yes! I'm gonna look at xui a little today

**Comment by goochjj** [comment]
See build-all.sh at the top of the repo.
