### ISSUE TITLE
No xui.events. Commit efd813bbfa6ff2ccafa92c9b289d173193560ca8 breaks xui.

### ISSUE THREAD

**Issue by zdennis** [brianleroux/xui#34]
The following commit efd813bbfa6ff2ccafa92c9b289d173193560ca8 breaks xui. It assumes xui.event is an object, but it is never assigned. Putting the following in our code fixes this:

<code>
xui.events = {};
</code>

Any ideas for long-term fix?

**Comment by remy** [comment]
Sorry - that's my changes. Yep - adding xui.events = {} fixes it.  I'm working on bespoke events, i.e. akin to jQuery special events - not particularly better, just simplified.

**Comment by filmaj** [comment]
+1, also commenting out line 63 of core/event.js fixes this.

**Comment by remy** [comment]
Fixed - sorry!
