### ISSUE TITLE
Result of expression '$(window).load' [undefined] is not a function.

### ISSUE THREAD

**Issue by buffpojken** [brianleroux/xui#35]
When running on just core.js - trying any kind of events fails with the
error above.

Is just running on core.js supported or are you supposed to use the entire more.js? The documentation is not very clear on this issue?

**Comment by remy** [comment]
XUI core doesn't provide event shortcuts, so you have to use:

`$(window).on('load', fn);`

That said, I'm about 90% sure that I want to move the shortcut handling in to core and ditch the more/events.js since it's so small now.

**Comment by buffpojken** [comment]
Thanks for the prompt reply!

Sadly, that doesn't seem to work either. On Safari 5.0.1 the following bombs with:

"Can't find variable: cache"

Code:
        $(window).on('load', function(e){
            alert("ninja");
        });

**Comment by remy** [comment]
Hmm - that's odd and shouldn't happen. Checking it out now for you.

**Comment by remy** [comment]
Odd. It works for me. I've got the latest build, and using xui-core.js from build-all.sh. Have you cleaned out and built from the latest?

**Comment by buffpojken** [comment]
Thanks for checking it out!
No, I've actually used the release from Google Code, is that an old release? 
Should I rebuild from this repo instead?

**Comment by buffpojken** [comment]
I'm testing a build from this repo right now!

**Comment by remy** [comment]
Cripes! Yep, use this repo, I'll kick Brian a bit to try to kill off the google repo - it's hugely out of date!

**Comment by buffpojken** [comment]
Okay, no wonder it was kind of wonky then =) I'll try it out with this repo instead and get back if the issue persist!

Thanks!

**Comment by buffpojken** [comment]
Yes, everything works as it should now - let's close this issue! 

Thanks for your help in resolving it, and yes - it might be a good idea to remove the google repos! 

Cheers!
