### ISSUE TITLE
Inconsistency between setStyle and getStyle

### ISSUE THREAD

**Issue by filmaj** [brianleroux/xui#36]
Taken straight out of the specs:

x$('#someElement').setStyle('backgroundColor','blue');
x$('#someElement').getStyle('background-color', function(v) { // ; });

How come we use two different strings to reference the same style property? Shouldn't this be consistent?

Thoughts?

**Comment by brianleroux** [comment]
yeah its stupid for sure. should probably use the css selector since it wouldn't require a translation

**Comment by filmaj** [comment]
ok my latest push on this just ends up supporting both approaches in both functions - easy enough.

**Comment by filmaj** [comment]
Like I said... both functions accept both types of styles.
