### ISSUE TITLE
Consolidating core and more

### ISSUE THREAD

**Issue by filmaj** [brianleroux/xui#37]
There is a 1k minified difference between core and more. Additionally, some functions in more, _I think_, are useless, and others I use all the fucking time. I think we should just combine the two.

I wanted to hack it all up right away but brian in his democratic way said, let's vote on it. So, here's a summary of functions present in more.js and my thoughts on whether to drop or incorporate into mainline. Please share your thoughts!

more/fx.js:

  native animations (i say kill it)

  webkit-transform-based animations (kill it)

more/dom.js:

  shortcut .html methods, i.e. .bottom() .top() etc. (incorporate)

more/base.js:

  add(), adds more dom elements to existing set. (kill it, I don't use it)

  end(), "Pops the last selector from XUI", wtf is this?

  first(), this is just get(0). typing get(0) is one less char so I don't know why someone 
would use first. kill it!

  get()... ya keep it.

  eq(): returns a collection containing element at given index. never use it, kill it.

  size(): return this.length. nuf said. kill it.

more/xhr.js:

  xhrjson - i love this function. keep it!

more/event.js:

  shortcut functions .click .touchstart etc. keep!

more/form.js:

  just helper functions for parsing forms. kill it, I never use it.

Please vote !!!!!!!

**Comment by alunny** [comment]
keep dom and event

I don't care about the rest

**Comment by brianleroux** [comment]
### native animations as plugin
- brian -1
- fil -1
- andrew -1

### more/dom.js shortcut .html methods, i.e. .bottom() .top()
- brian +1
- fil +1 
- andrew +1

### more/base.js:

add(), adds more dom elements to existing set. (kill it, I don't use it)
- brian -1
- fil -1
- andrew -1 

end(), "Pops the last selector from XUI", wtf is this?
- brian -1
- fil -1
- andrew -1 

first()
- brian +1
- fil -1
- andrew -1 

get()
- brian +1
- fil +1
- andrew -1 

eq(): returns a collection containing element at given index. never use it, kill it.
- brian -1
- fil -1
- andrew -1 

size(): return this.length. nuf said. kill it.
- brian -1
- fil -1
- andrew -1 

### more/xhr.js:

xhrjson - i love this function. keep it!
- brian -1
- fil +1
- andrew -1 

### more/event.js:

shortcut functions .click .touchstart etc. keep!
- brian +1
- fil +1
- andrew +1 

more/form.js:
- brian -1
- fil -1
- andrew -1 

just helper functions for parsing forms. kill it, I never use it.

**Comment by mwbrooks** [comment]
I vote the same as alunny:
- +1 DOM
- +1 Event

I don't use the rest.

**Comment by imhotep** [comment]
+1 DOM

**Comment by silentrob** [comment]
The Idea behind Add was to do things like x$('.selected').add('li:first').removeClass('baz');
Or x$('.selected').each(function(el) { this.add(el.firstChild); })

I think it has a use but maybe not super clear to see our not a popular pattern.

I tend to follow Fil's +1 DOM, +1 Event. drop first() in favor of get(0) or change get() to with no args to first()

if xhrjson is being used, I say we keep it. I dont care about the other xhr sugar methods.

If native animations work, I would like to keep them. They are hardware accelerators. and have many benefits over emily, plus less code.

**Comment by remy** [comment]
Equally $('selector').find('a').click(fn).end().doStuff2Selector() works by traversing up through the cache of selectors - a pattern that was supposed to help porting jquery plugins to xui

**Comment by brianleroux** [comment]
ok, from this conversation I'm thinking 
- add() ...I dunno. I wouldn't use it.
- kill first() and love the idea of get w/ no params being the same as get(0). reads nice.
- plugin called jquery-compat with end()
- native animations is less code than emile but there is currently only two devices (iphone/ipad) with hardware acccel. plugin.
- xhrjson: plugin

**Comment by remy** [comment]
- end() & and add() need to be together in the jquery-compat plugin.
- get() - kill it, it's a waste of time - you should do x$('selector')[0]

Otherwise agree with most of the other method changes.  I've never quite been sure of the grammer around bottom, top, etc - but that's more of documentation to go with it.

**Comment by filmaj** [comment]
Thanks for the comments guys. I kinda agree with remy - array syntax is fine with me instead of get(). Will save a few bytes too!
I'll set up xui organization repos (xui proper and xui-plugins) today sometime.

**Comment by remy** [comment]
Got some animation plugin good for you already - this will progressively enhance the tween method to detect CSS transitions and make use of them if they're available: http://github.com/remy/marbles2/blob/master/xui-anim.js

**Comment by silentrob** [comment]
remy, top and bottom make total sense in the context of list items x$('ul').bottom("add this");

**Comment by remy** [comment]
Sure - but what about the other elements :)  

Would <code>x$('div').top('&lt;p&gt;foo&lt;/p&gt;')</code> put the &lt;p&gt; on _top_ of the div or inside the div _at the_ top?  

I know the answer if I check the code (and based on the example you gave), but I'm not 100% sure by just looking at the syntax.  

Like I said, easily fixed with documentation and one simple example.

**Comment by filmaj** [comment]
This is all consolidated under the xui/xui repo.
