### ISSUE TITLE
context not passed to Sizzle in find()

### ISSUE THREAD

**Issue by bryfox** [brianleroux/xui#40]
Context on the find method can be lost when Sizzle is included with the library. Spec & patch here:

http://github.com/bryfox/xui/commit/c4ef1deb8f777b23a7262dee33bbbc86c83f6fec

...but I can't currently run specs on the platforms that include sizzle in their build profiles (IE/BB).

**Comment by filmaj** [comment]
Patch included in the new main repo (github.com/xui/xui)

Thanks bryfox!

**Comment by brianleroux** [comment]
...
