### ISSUE TITLE
hasClass() should return false on an empty set

### ISSUE THREAD

**Issue by bryfox** [brianleroux/xui#41]
Feel free to invalidate this, but (coming from jQuery, at least) I would expect hasClass() to return false for any class when tested against an empty set of elements.

Patch + spec: http://github.com/bryfox/xui/commit/64bc66a50c2147f420d277e6b482a3a04a56a74d

**Comment by filmaj** [comment]
Merged into latest build, but latest changes are going into a new repo:

www.github.com/xui/xui

Thanks for the fix and test!

**Comment by brianleroux** [comment]
thank you!
