### ISSUE TITLE
working xui-core.js

### ISSUE THREAD

**Issue by nulle** [brianleroux/xui#42]
Since the compiled xui-core on google code is terribly out of date, could anyone please be so nice as to provide some temporary link to the newest compiled version (dom, event, xhr)? Ive been banging my head against the table for couple of hours already to make one myself to no avail :(

**Comment by ghost** [comment]
Assuming you have git and ruby:

git clone git://github.com/brianleroux/xui.git
cd xui/
git submodule init
git submodule update
./build; ./build profile=bb

Files are in lib/

**Comment by luebbert42** [comment]
I had the same problem. Some hours ago I just wanted to have a quick look at XUI ending with installing git and ruby and modifying build scripts helplessly ;-) 

I am on Ubuntu and had to change "YAML" to "yaml" in line 2 to make it work. And I guess there is a "." to much in line 25. I changed it to:
`echo >> #{ hash["out"] }`

I suggest to put a little bit more information how to build a build into the README file, e.g.

"To create a build you need ruby. Having ruby installed proceed as follows:
git clone git://github.com/brianleroux/xui.git
cd xui/
git submodule init
git submodule update
./build; ./build profile=bb"

The files are in the lib directory".

**Comment by mikesten** [comment]
I just wasted an hour trying to figure out why I couldn't get a simple x$(window).on('load') working. Reading the docs. Re-reading the docs. Reading the source. I built my own core locally, copied the code in and it just worked. Please, please, please update the Google Code downloads - it makes for an incredibly frustrating first experience with XUI.

**Comment by brianleroux** [comment]
...
