### ISSUE TITLE
WebOS: Emile style normalization fails, (no child nodes exist)

### ISSUE THREAD

**Issue by clintandrewhall** [brianleroux/xui#43]
Not sure where this bug belongs, WebOS or Emile, but line 1300 of XUI-Full fails.  I suspect innerHTML is not honored if the node is not part of the DOM.

Take this test case, adapted from the Emile code:

var parseEl = document.createElement("div");
parseEl.innerHTML = "&lt;div style=\"height:100px\"&gt;&lt;/div&gt;";
Mojo.Log.error("NODE 0: " + parseEl.childNodes[0]);
var css = parseEl.childNodes[0].style;

Result: error: NODE 0: undefined

I'm writing up a better test case, but I thought I'd toss this out there to make sure I'm not crazy.
- Clint

**Comment by clintandrewhall** [comment]
Looks like github removed my markup on the parseEl.innerHTML line...

**Comment by brianleroux** [comment]
clint is this still an issue on the main xui/xui?

**Comment by clintandrewhall** [comment]
I haven't had a chance to test it yet... I will this weekend, though.  Sorry for the delay!
