### ISSUE TITLE
Suggestion: x$(selector).rmattr('attrname')

### ISSUE THREAD

**Issue by Charles74** [brianleroux/xui#46]
First of all, great library, thanks a bunch.
When dealing with disabled input boxes, such as button or submit, to enable them after they have been disabled a call to removeAttribute is required to remove the disabled attribute.  After a call to removeAttribute the button is enabled.  I added rmattr() to my local version, but I think other people might find it useful.

code: /**
          \* Remove an attribute
          *
          */
        rmattr: function(attribute) {
            this.each(function(el) {
                el.removeAttribute(attribute);
            });
        }

Thanks,
Charles

**Comment by remy** [comment]
I think the usage is low enough that it makes sense either as a part of a plugin suite or in xui-more.

**Comment by brianleroux** [comment]
could be added to github.com/xui/xui-plugins
