### ISSUE TITLE
ReferenceError: Can't find variable: $

### ISSUE THREAD

**Issue by cjimti** [brianleroux/xui#47]
event.js

line 155: $('body').fire('orientationchange'); 

should be
x$('body').fire('orientationchange');

**Comment by remy** [comment]
Damnit - I can never get the commit message right to close the issues on commit. Anyway - [fixed here](http://github.com/brianleroux/xui/commit/d704b5b95105a5e246b73f3f8f866fe4a0da5bca)

**Comment by cjimti** [comment]
cool. first time using xui and love it!
