### ISSUE TITLE
q.toString() == '[object NodeList]' is inadequate

### ISSUE THREAD

**Issue by drobert** [brianleroux/xui#48]
## In xui's find() method, there's the following conditional:

} else if (q.toString() == '[object NodeList]' {
   ele = slice(q);
## }

This doesn't support a call from someForm.elements, though, as that comes back as [object HTMLCollection]

For example, if a page contains a form with id 'someform'.  The following results in an empty xui object:

x$(document.getElementById('someform').elements);

Just changing the above conditional solves the problem (although may also need to be updated to include [object NamedNodeMap])):

} else if (q.toString() == '[object NodeList]' || q.toString() == '[object HTMLCollection]') {

**Comment by brianleroux** [comment]
sorry I don't quite follow (perhaps the way this formatted out) ...we're moving to github.com/xui/xui ---pls report bugs/fork there

**Comment by drobert** [comment]
Re-posted with some better formatting over at https://github.com/xui/xui/issues/issue/14
