### ISSUE TITLE
s60 regex unicode

### ISSUE THREAD

**Issue by nulle** [brianleroux/xui#50]
Due to some nokia regex bug that does not like unicode, in the dom <strong>function wrap</strong> (line 131), regular expression <code>/&#094;<([A-Z][A-Z0-9]*)([&#094;>]*)>([\s\S]*)<\/\1>/i</code> fails even on as simple tag as this <code>&lt;div&gt;š&lt;/div&gt;</code>, or in case of more nested tags returns wrong regexp.exec values, which can and usually does lead to some funky rendering.

While this is not exactly xui bug per se, I was wondering if anyone has / could come up with some reasonable solution for this symbian quirk and, of course, add it to the source ;)

p.s. Tested on nokia 5800 (s60v5)

**Comment by brianleroux** [comment]
no fix here for that...we'd be happy to accept a patch on github.com/xui/xui tho
