### ISSUE TITLE
Not working in Blackberry Bold 9700 using OS 5.0.0.469

### ISSUE THREAD

**Issue by mmcconna** [brianleroux/xui#51]
Got source from github on 22 Nov, built as instructions.

Works OK in Webkit, so build seems to have gone OK.

Does not work in Blackberry - the emulator (using Blackberry Bold 9700 using OS 5.0.0.469) doesn't process the file properly, i.e. if I put an alert('into XUI BB'); at the beginning of the js file it never even gets to it. This suggests the Blackberry JS interpreter detects some kind of syntax error.

What Blackberry software/models is XUIJS targetted against? Am I barking up the wrong tree thinking this should work?

If someone does have it working can they post a copy of the JS produced for Blackberry and I can check that my build worked OK?

**Comment by brianleroux** [comment]
the build creates a version w/ sizzle baked in for blackberry... check out the profiles

**Comment by mmcconna** [comment]
Shuold have made it clear that I did indeed run it with profile=bb. 

Initially i got errors during build " - sh could not find echo." or words to that effect. I aliased echo. to echo and got no more build errors.

I would deeply appreciate a post of a core-bb.js file so I can compare it and figure out if there is anything wrong with my build process or if I should reopen this as an issue with Blackberry compatibility.

**Comment by brianleroux** [comment]
did you:

git submodule init && git submodule update

to pull in sizzle?

**Comment by brianleroux** [comment]
did you:

git submodule init && git submodule update

to pull in sizzle?

**Comment by mmcconna** [comment]
Yes, I did all the git stuff.

Actually I think this was a problem with the Blackberry emulator/Visual Studio combination. I recopied everything in a new project and it "just worked."

In case anyone else is reading this, here is what I did to get the xuijs built in ubuntu (v.8 LTS) (look out for rogue newlines, I can't seem to make these work).

apt-get install git
apt-get install libyaml
apt-get install ruby

can't remember if there was a apt-get install libyaml-ruby at this point.

chdir to the directory you want to store stuff in:

git clone https://github.com/brianleroux/xui.git  
git submodule init  
git submodule update  

Then edit the downloaded build file to replace "require 'YAML';" with "require 'yaml';"

Then (build process appears to use a command echo. which may be a typo) 

ln -s /bin/echo ~/bin/echo.

then (assuming you need webkit, blackberry and mobile IE (haven't tested the last yet!)
./build  
./build profile=bb  
./build profile=ie  

I didn't bother to install java to do the minified versions, I will use an online minifier or more likely do minification on the js files on the fly via the web server like the compression.

Thanks for the code - it certainly seems compact and efficient.
